version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.js
